name: linked-squad
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - streamlit
  - pydantic
  - requests
  - python-dotenv
  - numpy
  - pandas
  - matplotlib
  - pytest
  - pip:
      - langchain
      - langgraph
      - langchain-google-genai
      - streamlit-chat
      - apify-client
